---
- name: Deploy Configurations via CloudVision
  hosts: FABRIC
  gather_facts: false
  connection: local
  tasks:
    - name: Deploy Configurations via CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.4.165
        cv_token: "{{ lookup('file', '~/.cvp_token') }}"
        cv_verify_certs: false
